# Generated by Django 3.0.7 on 2020-06-18 04:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=30)),
                ('libelle', models.CharField(max_length=100)),
                ('pays', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=30, unique=True)),
                ('description', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Serveur',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nr_serveur', models.IntegerField(unique=True)),
                ('nom', models.CharField(max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nr_table', models.IntegerField(unique=True)),
                ('nom', models.CharField(max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=30, unique=True)),
                ('description', models.CharField(max_length=100, null=True)),
                ('prix', models.DecimalField(decimal_places=2, max_digits=5)),
                ('photo', models.ImageField(null=True, upload_to='photos/')),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produits', to='restaurant.Categorie')),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produits', to='restaurant.Menu')),
            ],
        ),
        migrations.CreateModel(
            name='Details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.IntegerField()),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='restaurant.Produit')),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='restaurant.Table')),
            ],
        ),
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nr_commande', models.TextField(max_length=10, unique=True)),
                ('composition', models.TextField(max_length=1000)),
                ('total', models.DecimalField(decimal_places=2, max_digits=5)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('serveur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commandes', to='restaurant.Serveur')),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commandes', to='restaurant.Table')),
            ],
        ),
    ]
