# Generated by Django 3.0.7 on 2020-06-18 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categorie',
            name='pays',
        ),
        migrations.AddField(
            model_name='produit',
            name='pays',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
