# Generated by Django 3.0.7 on 2020-06-18 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_auto_20200618_0706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorie',
            name='libelle',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
