# Generated by Django 3.0.7 on 2020-06-18 05:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0003_auto_20200618_0713'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categorie',
            old_name='type',
            new_name='type_cat',
        ),
    ]
