# Generated by Django 3.0.6 on 2020-06-21 21:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0006_menu_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menu',
            options={'verbose_name': 'Menu', 'verbose_name_plural': 'Menus'},
        ),
    ]
