# Generated by Django 3.0.6 on 2020-06-21 22:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0007_auto_20200621_2356'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menu',
            options={},
        ),
    ]
