# Generated by Django 3.0.6 on 2020-07-07 00:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0008_remove_produit_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commande',
            name='total',
        ),
        migrations.AddField(
            model_name='commande',
            name='commander',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='produit',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
        migrations.RemoveField(
            model_name='commande',
            name='composition',
        ),
        migrations.AlterField(
            model_name='commande',
            name='nr_commande',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.CreateModel(
            name='Choix',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.IntegerField(default=1)),
                ('commander', models.BooleanField(default=False)),
                ('creer', models.DateTimeField(auto_now_add=True)),
                ('choix', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurant.Produit')),
            ],
        ),
        migrations.AddField(
            model_name='commande',
            name='composition',
            field=models.ManyToManyField(to='restaurant.Choix'),
        ),
    ]
