# Generated by Django 3.0.6 on 2020-07-11 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0008_auto_20200622_0037'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Details',
        ),
    ]
