# Generated by Django 3.0.6 on 2020-07-08 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0009_auto_20200707_0242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produit',
            name='photo',
            field=models.ImageField(null=True, upload_to='restaurant'),
        ),
    ]
