# Generated by Django 3.0.6 on 2020-07-08 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0010_auto_20200708_1330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produit',
            name='photo',
            field=models.ImageField(null=True, upload_to='produits/'),
        ),
        migrations.DeleteModel(
            name='Details',
        ),
    ]
